CREATE TEMPORARY TABLE IF NOT EXISTS male_pop_text(zip int, malepop int)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

CREATE TABLE IF NOT EXISTS male_pop_orc(zip int, malepop int) 
ROW FORMAT DELIMITED 
FIELDS TERMINATED BY ',' 
STORED AS ORC;

LOAD DATA LOCAL INPATH '/root/exercise2/data/zip_malepop.csv' OVERWRITE INTO TABLE male_pop_text;

INSERT OVERWRITE TABLE male_pop_orc SELECT * FROM male_pop_text;

